In [1]:
import numpy as np
import pandas as pd

In [2]:
data_raw = pd.read_csv("../data/raw/Telco-Customer-Churn.csv")

In [5]:
data_raw.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
data_raw.shape

(7043, 21)

In [11]:
data_raw.rename(columns = {"gender":"Gender", "tenure": "Tenure","customerID":"CustomerID",'InternetService':'InternetServiceType','Contract':'ContractType'}, inplace =True)
df_raw = data_raw.copy()

In [13]:
df_raw['Partner'] = df_raw.Partner.map({'Yes':1,'No':0})
df_raw['Dependents'] = df_raw.Dependents.map({'Yes':1,'No':0})

df_raw['PhoneService'] = df_raw.PhoneService.map({'Yes':1,'No':0})
df_raw['MultipleLines'] = df_raw.MultipleLines.map({'Yes':1,'No':0,'No phone service':0})

df_raw['InternetService'] = df_raw.InternetServiceType.map({'DSL':1,'Fiber optic':1,'No':0})
df_raw['OnlineSecurity'] = df_raw.OnlineSecurity.map({'Yes':1,'No':0,'No internet service':0})
df_raw['OnlineBackup'] = df_raw.OnlineBackup.map({'Yes':1,'No':0,'No internet service':0})
df_raw['DeviceProtection'] = df_raw.DeviceProtection.map({'Yes':1,'No':0,'No internet service':0})
df_raw['TechSupport'] = df_raw.TechSupport.map({'Yes':1,'No':0,'No internet service':0})
df_raw['StreamingTV'] = df_raw.StreamingTV.map({'Yes':1,'No':0,'No internet service':0})
df_raw['StreamingMovies'] = df_raw.StreamingMovies.map({'Yes':1,'No':0,'No internet service':0})

df_raw['IsContracted'] = df_raw.ContractType.map({'One year':1,'Two year':1,'Month-to-month':0})
df_raw['PaperlessBilling'] = df_raw.PaperlessBilling.map({'Yes':1,'No':0})
df_raw['Churn'] = df_raw.Churn.map({'Yes':1,'No':0})

df_raw.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetServiceType,OnlineSecurity,...,StreamingTV,StreamingMovies,ContractType,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,InternetService,IsContracted
0,7590-VHVEG,Female,0,1,0,1,0,0,DSL,0,...,0,0,Month-to-month,1,Electronic check,29.85,29.85,0,1,0
1,5575-GNVDE,Male,0,0,0,34,1,0,DSL,1,...,0,0,One year,0,Mailed check,56.95,1889.5,0,1,1
2,3668-QPYBK,Male,0,0,0,2,1,0,DSL,1,...,0,0,Month-to-month,1,Mailed check,53.85,108.15,1,1,0
3,7795-CFOCW,Male,0,0,0,45,0,0,DSL,1,...,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0,1,1
4,9237-HQITU,Female,0,0,0,2,1,0,Fiber optic,0,...,0,0,Month-to-month,1,Electronic check,70.70,151.65,1,1,0

In [15]:
df_raw.isnull().sum()

CustomerID             0
Gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
Tenure                 0
PhoneService           0
MultipleLines          0
InternetServiceType    0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
ContractType           0
PaperlessBilling       0
PaymentMethod          0
MonthlyCharges         0
TotalCharges           0
Churn                  0
InternetService        0
IsContracted           0
dtype: int64

In [17]:
df_raw.dtypes

CustomerID              object
Gender                  object
SeniorCitizen            int64
Partner                  int64
Dependents               int64
Tenure                   int64
PhoneService             int64
MultipleLines            int64
InternetServiceType     object
OnlineSecurity           int64
OnlineBackup             int64
DeviceProtection         int64
TechSupport              int64
StreamingTV              int64
StreamingMovies          int64
ContractType            object
PaperlessBilling         int64
PaymentMethod           object
MonthlyCharges         float64
TotalCharges            object
Churn                    int64
InternetService          int64
IsContracted             int64
dtype: object

In [23]:
# Converting TotalCharges into Numeric, but some of the records are empty, so first we need to deal with them
print(df_raw[df_raw['TotalCharges']==' '][['MonthlyCharges','TotalCharges']]) 
df_raw.loc[df_raw['TotalCharges']==' ','TotalCharges'] = np.nan

Empty DataFrame
Columns: [MonthlyCharges, TotalCharges]
Index: []

In [27]:
# first we convert TotalCharges to float and then replace with tenure * monthly charges
df_raw['TotalCharges'] = df_raw['TotalCharges'].astype('float64')
df_raw.loc[df_raw['TotalCharges']==np.nan,'TotalCharges'] = df_raw['MonthlyCharges'] * df_raw['Tenure']

In [33]:
def createAnyInternetService(row):
    if ((row["OnlineSecurity"]==1)| (row['OnlineBackup']==1) | (row['DeviceProtection']==1) | (row['TechSupport']==1) 
        | (row['StreamingTV']==1) | (row['StreamingMovies']==1)):
        return 1
    else:
        return 0 
                
df_raw['AnyInternetService'] = df_raw.apply(lambda row: createAnyInternetService(row), axis = 1)
df_raw.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetServiceType,OnlineSecurity,...,StreamingMovies,ContractType,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,InternetService,IsContracted,AnyInternetService
0,7590-VHVEG,Female,0,1,0,1,0,0,DSL,0,...,0,Month-to-month,1,Electronic check,29.85,29.85,0,1,0,1
1,5575-GNVDE,Male,0,0,0,34,1,0,DSL,1,...,0,One year,0,Mailed check,56.95,1889.50,0,1,1,1
2,3668-QPYBK,Male,0,0,0,2,1,0,DSL,1,...,0,Month-to-month,1,Mailed check,53.85,108.15,1,1,0,1
3,7795-CFOCW,Male,0,0,0,45,0,0,DSL,1,...,0,One year,0,Bank transfer (automatic),42.30,1840.75,0,1,1,1
4,9237-HQITU,Female,0,0,0,2,1,0,Fiber optic,0,...,0,Month-to-month,1,Electronic check,70.70,151.65,1,1,0,0

In [35]:
df_raw.drop_duplicates()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetServiceType,OnlineSecurity,...,StreamingMovies,ContractType,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,InternetService,IsContracted,AnyInternetService
0,7590-VHVEG,Female,0,1,0,1,0,0,DSL,0,...,0,Month-to-month,1,Electronic check,29.85,29.85,0,1,0,1
1,5575-GNVDE,Male,0,0,0,34,1,0,DSL,1,...,0,One year,0,Mailed check,56.95,1889.50,0,1,1,1
2,3668-QPYBK,Male,0,0,0,2,1,0,DSL,1,...,0,Month-to-month,1,Mailed check,53.85,108.15,1,1,0,1
3,7795-CFOCW,Male,0,0,0,45,0,0,DSL,1,...,0,One year,0,Bank transfer (automatic),42.30,1840.75,0,1,1,1
4,9237-HQITU,Female,0,0,0,2,1,0,Fiber optic,0,...,0,Month-to-month,1,Electronic check,70.70,151.65,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,1,1,24,1,1,DSL,1,...,1,One year,1,Mailed check,84.80,1990.50,0,1,1,1
7039,2234-XADUH,Female,0,1,1,72,1,1,Fiber optic,0,...,1,One year,1,Credit card (automatic),103.20,7362.90,0,1,1,1
7040,4801-JZAZL,Female,0,1,1,11,0,0,DSL,1,...,0,Month-to-month,1,Electronic check,29.60,346.45,0,1,0,1
7041,8361-LTMKD,Male,1,1,0,4,1,1,Fiber optic,0,...,0,Month-to-month,1,Mailed check,74.40,306.60,1,1,0,0
7042,3186-AJIEK,Male,0,0,0,66,1,0,Fiber optic,1,...,1,Two year,1,Bank transfer (automatic),105.65,6844.50,0,1,1,1

In [37]:
df_raw.nunique()

CustomerID             7043
Gender                    2
SeniorCitizen             2
Partner                   2
Dependents                2
Tenure                   73
PhoneService              2
MultipleLines             2
InternetServiceType       3
OnlineSecurity            2
OnlineBackup              2
DeviceProtection          2
TechSupport               2
StreamingTV               2
StreamingMovies           2
ContractType              3
PaperlessBilling          2
PaymentMethod             4
MonthlyCharges         1585
TotalCharges           6531
Churn                     2
InternetService           2
IsContracted              2
AnyInternetService        2
dtype: int64

In [39]:
df_raw.dtypes

CustomerID              object
Gender                  object
SeniorCitizen            int64
Partner                  int64
Dependents               int64
Tenure                   int64
PhoneService             int64
MultipleLines            int64
InternetServiceType     object
OnlineSecurity           int64
OnlineBackup             int64
DeviceProtection         int64
TechSupport              int64
StreamingTV              int64
StreamingMovies          int64
ContractType            object
PaperlessBilling         int64
PaymentMethod           object
MonthlyCharges         float64
TotalCharges           float64
Churn                    int64
InternetService          int64
IsContracted             int64
AnyInternetService       int64
dtype: object

In [43]:
 df_raw.to_csv("../data/cleaned/data_cleaned.csv", index=False)